### ISSUE TITLE
HiDPI text editor: wrong span positions?

### ISSUE THREAD

**Issue by tinchodias** [plantec/Album#25]
<img width="543" alt="Screen Shot 2022-10-13 at 09 31 24" src="https://user-images.githubusercontent.com/3044265/195596648-daba0b58-0f46-4823-84b3-e7cb61b8e6aa.png">

Code:
```
"Set up"
AeFontManager resetGlobalInstance.
AeDownloadedFont ensureAllDownloadedAt: AeFilesystemResources downloadedFontsDirectory.
AeFontManager globalInstance
	scanDirectory: AeFilesystemResources fontsDirectory;
	scanDefaultDirectories.

"Doesn't work! symbols should be replaced"
text := 'a := A->B->>C <= c|=>d~~>e.' asRopedText
	fontName: 'Cascadia Code'; fontSize: 30;
	yourself.
text onAlbum openInOblSpace.
```

Steps to reproduce in a MacBook (maybe in any HiDPI screen):
1. Select "SDL2 Alexandrie" Bloc host in System settings
2. Evaluate the code above

When the host is "Morphic Alexandrie", it looks nice.

**Comment by plantec** [comment]
strange that it works fine with Morphia-Alexandrie...
I've noticed the the measured advance seems wrong for some letters as C, c, a ... (ok for A)

**Comment by plantec** [comment]
I wanted to test it on Windows but Alexandrie don't load on windows.

**Comment by tinchodias** [comment]
Probably there was an error on the postLoad action of the
BaselineOfAlexandrie, because it logs in the terminal the version of
Harfbuzz, among others, and it doesn't find it.

I plan to try it on windows and linux today. For the moment we can get the
harfbuzz DLL the same as Esteban's gtk bindings, from this zip:
http://files.pharo.org/vm/pharo-spur64-headless/win/latest-win64-GTK.zip

Martín

**Comment by tinchodias** [comment]
On Mon, Oct 17, 2022 at 10:45 AM Martin Dias ***@***.***> wrote:

> Probably there was an error on the postLoad action of the
> BaselineOfAlexandrie, because it logs in the terminal the version of
> Harfbuzz, among others, and it doesn't find it.
>
> I plan to try it on windows and linux today. For the moment we can get the
> harfbuzz DLL the same as Esteban's gtk bindings, from this zip:
> http://files.pharo.org/vm/pharo-spur64-headless/win/latest-win64-GTK.zip
>
> I tried and failed to add harfbuzz DLL on my windows 10.
But it is disabled by default, so I only removed what was raising the
error: a log in the BaselineOfAlexandrie.
Maybe it now works on Windows. I'll try tomorrow.

Cheers,
Martín

**Comment by tinchodias** [comment]
On Tue, Oct 18, 2022 at 12:09 AM Martin Dias ***@***.***> wrote:

>
>
> On Mon, Oct 17, 2022 at 10:45 AM Martin Dias ***@***.***> wrote:
>
>> Probably there was an error on the postLoad action of the
>> BaselineOfAlexandrie, because it logs in the terminal the version of
>> Harfbuzz, among others, and it doesn't find it.
>>
>> I plan to try it on windows and linux today. For the moment we can get
>> the harfbuzz DLL the same as Esteban's gtk bindings, from this zip:
>> http://files.pharo.org/vm/pharo-spur64-headless/win/latest-win64-GTK.zip
>>
>> I tried and failed to add harfbuzz DLL on my windows 10.
> But it is disabled by default, so I only removed what was raising the
> error: a log in the BaselineOfAlexandrie.
> Maybe it now works on Windows. I'll try tomorrow.
>

It works when installing a recent harfbuzz + dependencies.
Unzip this into the pharo-vm directory (replacing some dlls) made it work:
https://github.com/harfbuzz/harfbuzz/releases/download/5.2.0/harfbuzz-win64-5.2.0.zip

**Comment by tinchodias** [comment]
On Wed, Oct 19, 2022 at 5:07 AM Martin Dias ***@***.***> wrote:

>
>
> On Tue, Oct 18, 2022 at 12:09 AM Martin Dias ***@***.***> wrote:
>
>>
>>
>> On Mon, Oct 17, 2022 at 10:45 AM Martin Dias ***@***.***>
>> wrote:
>>
>>> Probably there was an error on the postLoad action of the
>>> BaselineOfAlexandrie, because it logs in the terminal the version of
>>> Harfbuzz, among others, and it doesn't find it.
>>>
>>> I plan to try it on windows and linux today. For the moment we can get
>>> the harfbuzz DLL the same as Esteban's gtk bindings, from this zip:
>>> http://files.pharo.org/vm/pharo-spur64-headless/win/latest-win64-GTK.zip
>>>
>>> I tried and failed to add harfbuzz DLL on my windows 10.
>> But it is disabled by default, so I only removed what was raising the
>> error: a log in the BaselineOfAlexandrie.
>> Maybe it now works on Windows. I'll try tomorrow.
>>
>
> It works when installing a recent harfbuzz + dependencies.
> Unzip this into the pharo-vm directory (replacing some dlls) made it work:
>
> https://github.com/harfbuzz/harfbuzz/releases/download/5.2.0/harfbuzz-win64-5.2.0.zip
>

Bah, the dlls can be located on the same directory as the image, too.

**Comment by tinchodias** [comment]
This is fixed, I guess.

**Comment by tinchodias** [comment]
This is too old
