### ISSUE TITLE
AnObsoleteBrStencilBuilder superclass

### ISSUE THREAD

**Issue by Nyan11** [plantec/Album#32]
Hello,

# Description

I was trying to load the project using:

```st
[	Metacello new
        baseline: 'Toplo';
        repository: 'github://plantec/Toplo/src';
        onConflictUseIncoming;
        ignoreImage;
        load.
    ]	on: MCMergeOrLoadWarning
      do: [ :warning | warning load ]
```

and an error occured:

`errorKeyNotFound:` for `AnObsoleteBrStencilBuilder`

After looking the commit https://github.com/plantec/Album/commit/658331617d9aa8135100b7dac5743f956ac7702f

I saw that the class: `AlbTextAdornmentStencilBuilder` as a problem.

```st
Class {
	#name : #AlbTextAdornmentStencilBuilder,
	"#superclass : #BrStencilBuilder," "<- old version"
	#superclass : #AnObsoleteBrStencilBuilder,
	#instVars : [
		'editorElement',
		'segmentPiece'
```

severity: high

# Other

pharo image : Pharo-12.0.0+build.204.sha.99c16dca53c1b77a4a5d7dad7c56c2d092a785c1 (64 Bit)
album version  : [6583316] - 2023-04-20

**Comment by tinchodias** [comment]
Hi, sorry for the delay. Is this issue still valid, or fixed?

**Comment by plantec** [comment]
The NU package should not be loaded by default. (NU is for Not Used )

**Comment by tinchodias** [comment]
>1 year now, let's close it
